{{- with .Values.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
provisioner: {{ .provisioner }}
{{- if .allowVolumeExpansion }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
{{- end }}
{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .reclaimPolicy }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}
volumeBindingMode: {{ .volumeBindingMode }}
{{- with .mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}