apiVersion: v2
name: file-server
description: The file servers helm chart for k8s
kubeVersion: ">= 1.28.0"
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: ingress-nginx
    version: 4.10.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled