deployments:
  files:
    strategy: Recreate
  identity:
    strategy: Recreate
  frontend:
    strategy: Recreate
  adminer:
    strategy: Recreate

statefulSets:
  db:
    volumeClaimTemplates:
      storageClassName: null

persistentVolumeClaims:
  fs-storage:
    storageClassName: null

storageClass: null

issuers: null

ingress:
  main-ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    tls:
      - hosts:
          - fileserver.test
        secretName: fileserver-tls
    hosts:
      - host: fileserver.test
        paths:
          - path: /
            pathType: Prefix
            name: frontend
          - path: /api/identity
            pathType: Prefix
            name: identity
          - path: /api/files
            pathType: Prefix
            name: files
  adminer:
    tls:
      - hosts:
          - fileserver.test
        secretName: fileserver-tls
    hosts:
      - host: fileserver.test
        paths:
          - path: /adminer/(.*)
            pathType: ImplementationSpecific
            name: adminer

ingress-nginx:
  enabled: false